AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:

 CaseRestApi:
  Type: "AWS::ApiGateway::RestApi"
  Properties:
   Name: "CaseRestApi"
   FailOnWarnings: "true"
   
 CaseResource:
  Type: "AWS::ApiGateway::Resource"
  Properties:
   ParentId : 
    Fn::GetAtt:
     - "CaseRestApi"
     - "RootResourceId"
   PathPart: "case"
   RestApiId:
    Ref: "CaseRestApi"  
 
 GetCaseMethod:
  Type: "AWS::ApiGateway::Method"
  Properties:
   HttpMethod: "GET"
   AuthorizationType: "NONE"
   ResourceId:
    Ref: "CaseResource"
   RestApiId:
    Ref: "CaseRestApi"
   Integration:
    Type: "AWS_PROXY"
    Uri :           
     Fn::Join:
      - ""
      - - "arn:aws:apigateway:"
        - !Ref "AWS::Region"
        - ":lambda:path/"
        - "/2015-03-31/functions/"
        - Fn::GetAtt:
          - GetCaseFunction
          - Arn
        - "/invocations"
    IntegrationHttpMethod: "GET"

 GetCaseFunction:
  Type: AWS::Serverless::Function
  Properties:
   CodeUri: target/case-manager-1.0.0.jar
   Handler: com.sreejith824.pwapoc.creditcase.handler.GetCaseFunctionHandler::handleRequest
   Runtime: java8
   MemorySize: 512
   Timeout: 30
   Role: "arn:aws:iam::616030043679:role/pwapoc-case-stackv3-LambdaExecutionRole-1DZHB1WV8I1OI"