AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
      
 GetCaseFunction:
  Type: AWS::Serverless::Function
  Properties:
   CodeUri: target/case-manager-1.0.0.jar
   Handler: com.sreejith824.pwapoc.creditcase.handler.GetCaseFunctionHandler::handleRequest
   Runtime: java8
   MemorySize: 512
   Timeout: 30
   Role: "arn:aws:iam::616030043679:role/pwapoc-case-stackv3-LambdaExecutionRole-1DZHB1WV8I1OI" 
   Events:
    GetCase:
     Type: Api
     Properties:
      Path: /api/case
      Method: get
      Integration: lambda
      Request : 
       template :
        application/json: >
         {
          "caseId" : "case123"
         }  
       
